apiVersion: v1
kind: Service
metadata:
  name: hello-java-service
spec:
  type: LoadBalancer
  selector:
    app: hello-java
  ports:
    - protocol: TCP
      port: 8282       # External port
      targetPort: 8991 # Internal container port
